## 1. Data Loading

In [1]:
import pandas as pd
import os

file_path = "../data/raw/amazon_ecommerce_1M.csv"

df = pd.read_csv(file_path)

# 2. Data Profiling

In [2]:
print(df.shape)

(1000000, 20)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 20 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   user_id             1000000 non-null  object
 1   product_id          1000000 non-null  object
 2   category            1000000 non-null  object
 3   subcategory         1000000 non-null  object
 4   brand               1000000 non-null  object
 5   price               1000000 non-null  float64
 6   discount            1000000 non-null  float64
 7   final_price         1000000 non-null  float64
 8   rating              1000000 non-null  float64
 9   review_count        1000000 non-null  int64
 10  stock               1000000 non-null  int64
 11  seller_id           1000000 non-null  object
 12  seller_rating       1000000 non-null  float64
 13  purchase_date       1000000 non-null  object
 14  shipping_time_days  1000000 non-null  int64
 15  location            1000000 non-null  object
 16  device              1000000 non-null  object
 17  payment_method      1000000 non-null  object
 18  is_returned         1000000 non-null  bool
 19  delivery_status     1000000 non-null  object
dtypes: bool(1), float64(5), int64(3), object(11)
memory usage: 145.9+ MB

In [4]:
df.head()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43,71,S2679,4.3,2025-03-04,6,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13,119,S9279,4.9,2025-12-12,1,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46,229,S5557,4.9,2024-04-25,1,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6,52,S2519,3.1,2025-12-18,2,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48,274,S3045,2.6,2024-05-16,5,Delhi,Web,UPI,False,Delayed

In [5]:
df.tail()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
999995,U485987,P55818,Sports,Cycling,Sony,1478.80,36.55,938.34,4.1,15,392,S7795,4.2,2025-03-12,1,Delhi,Mobile App,Credit Card,False,Delivered
999996,U917934,P59467,Sports,Cycling,H&M,4532.12,5.22,4295.44,4.2,32,17,S4919,3.6,2025-11-04,5,Hyderabad,Mobile App,Debit Card,False,In Transit
999997,U667215,P21840,Electronics,Laptop,Lenovo,14986.75,29.00,10640.50,4.5,115,382,S4196,2.8,2025-11-06,5,Hyderabad,Web,Debit Card,False,In Transit
999998,U640883,P46092,Clothing,Men,Samsung,4473.67,21.43,3514.86,4.2,14,451,S3812,2.9,2025-02-25,1,Delhi,Tablet,Debit Card,False,Delivered
999999,U220301,P91830,Electronics,Laptop,Samsung,71369.83,8.25,65480.69,5.0,36,109,S1286,2.8,2025-05-28,5,Chennai,Mobile App,UPI,False,Delayed

In [6]:
df.isnull().sum()

user_id               0
product_id            0
category              0
subcategory           0
brand                 0
price                 0
discount              0
final_price           0
rating                0
review_count          0
stock                 0
seller_id             0
seller_rating         0
purchase_date         0
shipping_time_days    0
location              0
device                0
payment_method        0
is_returned           0
delivery_status       0
dtype: int64

In [7]:
df.duplicated().sum()

0

In [8]:
categorical_columns = [
    "category",
    "subcategory",
    "brand",
    "device",
    "payment_method",
    "delivery_status"
]

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].nunique())
    print(df[col].value_counts().head(10))

--- category ---
5
category
Home           200922
Electronics    200038
Sports         199889
Clothing       199824
Beauty         199327
Name: count, dtype: int64

--- subcategory ---
16
subcategory
Decor        67260
Kitchen      67021
Kids         67006
Outdoor      66795
Fitness      66780
Skincare     66696
Furniture    66641
Men          66599
Makeup       66331
Cycling      66314
Name: count, dtype: int64

--- brand ---
12
brand
LG         83882
Puma       83627
Lenovo     83542
Samsung    83535
HP         83520
Sony       83479
Boat       83448
Nike       83316
Zara       83218
Apple      83119
Name: count, dtype: int64

--- device ---
3
device
Mobile App    333637
Web           333297
Tablet        333066
Name: count, dtype: int64

--- payment_method ---
4
payment_method
Cash on Delivery    250388
Credit Card         250324
UPI                 249951
Debit Card          249337
Name: count, dtype: int64

--- delivery_status ---
4
delivery_status
Delivered     295234
Delayed       294983
In Transit    293793
Returned      115990
Name: count, dtype: int64

In [9]:
numeric_columns = [
    "price",
    "discount",
    "final_price",
    "rating",
    "review_count",
    "stock",
    "shipping_time_days"
]

df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
price,1000000.0,13224.119093,18079.626921,200.03,2700.1475,4971.830,14134.4825,79999.70
discount,1000000.0,28.996161,14.681077,5.00,16.9100,28.070,39.2400,70.00
final_price,1000000.0,9938.876985,14271.885557,101.46,1705.9300,3790.795,10384.4400,75831.11
rating,1000000.0,3.927226,0.519443,1.50,3.6000,3.900,4.3000,5.00
review_count,1000000.0,32.626704,43.382201,0.00,10.0000,20.000,39.0000,3408.00
stock,1000000.0,250.023345,144.567038,0.00,125.0000,250.000,375.0000,500.00
shipping_time_days,1000000.0,3.166389,1.674178,1.00,2.0000,3.000,5.0000,6.00

In [10]:
df["purchase_date"].head()

0    2025-03-04
1    2025-12-12
2    2024-04-25
3    2025-12-18
4    2024-05-16
Name: purchase_date, dtype: object

In [11]:
df["purchase_date"].dtype

dtype('O')

In [12]:
df["user_id"].nunique()

603815

In [13]:
df["product_id"].nunique()

89999

In [14]:
df["seller_id"].nunique()

9000

In [15]:
df[["user_id", "product_id", "purchase_date"]].duplicated().sum()

0

## 3. Data Quality Validation

In [16]:
duplicate_count = df.duplicated().sum()

print(duplicate_count)

0

In [17]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'])

In [18]:
print("Minimum date:", df['purchase_date'].min())
print("Maximum date:", df['purchase_date'].max())
print("Number of invalid dates:", df['purchase_date'].isna().sum())

Minimum date: 2024-03-31 00:00:00
Maximum date: 2026-03-31 00:00:00
Number of invalid dates: 0

In [19]:
expected_final_price = (
    df['price'] * (1 - df['discount'] / 100)
)

price_difference = (
    df['final_price'] - expected_final_price
).abs()

print("Maximum price difference:", price_difference.max())
print("Rows with price inconsistency:", (price_difference > 0.01).sum())

Maximum price difference: 3.986772000003839
Rows with price inconsistency: 935928

In [20]:
print("Price <= 0:", (df['price'] <= 0).sum())
print("Discount < 0:", (df['discount'] < 0).sum())
print("Discount > 100:", (df['discount'] > 100).sum())
print("Final price <= 0:", (df['final_price'] <= 0).sum())
print("Rating < 1:", (df['rating'] < 1).sum())
print("Rating > 5:", (df['rating'] > 5).sum())
print("Stock < 0:", (df['stock'] < 0).sum())
print("Shipping time <= 0:", (df['shipping_time_days'] <= 0).sum())

Price <= 0: 0
Discount < 0: 0
Discount > 100: 0
Final price <= 0: 0
Rating < 1: 0
Rating > 5: 0
Stock < 0: 0
Shipping time <= 0: 0

In [21]:
categorical_columns = [
    'category',
    'subcategory',
    'brand',
    'location',
    'device',
    'payment_method',
    'delivery_status'
]

for col in categorical_columns:
    print(f"\n{col}")
    print(df[col].unique())

category
['Electronics' 'Sports' 'Beauty' 'Home' 'Clothing']

subcategory
['Mobile' 'Outdoor' 'Fitness' 'Makeup' 'Decor' 'Furniture' 'Kids' 'Women'
 'Cycling' 'Laptop' 'Skincare' 'Men' 'Camera' 'Kitchen' 'Haircare'
 'Headphones']

brand
['H&M' 'Samsung' 'Sony' 'HP' 'Adidas' 'Apple' 'Nike' 'Boat' 'Zara' 'LG'
 'Lenovo' 'Puma']

location
['Bangalore' 'Delhi' 'Chennai' 'Mumbai' 'Hyderabad']

device
['Tablet' 'Mobile App' 'Web']

payment_method
['UPI' 'Credit Card' 'Debit Card' 'Cash on Delivery']

delivery_status
['Returned' 'In Transit' 'Delayed' 'Delivered']

In [22]:
pd.crosstab(
    df['is_returned'],
    df['delivery_status']
)

delivery_status  Delayed  Delivered  In Transit  Returned
is_returned
False             294983     295234      293793         0
True                   0          0           0    115990

## 4. Data Cleaning

In [23]:
df_clean = df.copy()

print("Size data:", df_clean.shape)

Size data: (1000000, 20)

In [24]:
df_clean['purchase_date'] = pd.to_datetime(df_clean['purchase_date'])

print(df_clean['purchase_date'].dtype)

datetime64[ns]

In [25]:
categorical_columns = [
    'category',
    'subcategory',
    'brand',
    'location',
    'device',
    'payment_method',
    'delivery_status'
]

for col in categorical_columns:
    df_clean[col] = df_clean[col].str.strip()

## 5. Data Transformation

In [26]:
# Membuat kolom turunan dari purchase_date

df_clean['purchase_year'] = df_clean['purchase_date'].dt.year
df_clean['purchase_month'] = df_clean['purchase_date'].dt.month
df_clean['purchase_month_name'] = df_clean['purchase_date'].dt.month_name()
df_clean['purchase_quarter'] = df_clean['purchase_date'].dt.quarter
df_clean['purchase_day'] = df_clean['purchase_date'].dt.day
df_clean['purchase_day_name'] = df_clean['purchase_date'].dt.day_name()

In [27]:
df_clean[
    [
        'purchase_date',
        'purchase_year',
        'purchase_month',
        'purchase_month_name',
        'purchase_quarter',
        'purchase_day',
        'purchase_day_name'
    ]
].head()

,purchase_date,purchase_year,purchase_month,purchase_month_name,purchase_quarter,purchase_day,purchase_day_name
0,2025-03-04,2025,3,March,1,4,Tuesday
1,2025-12-12,2025,12,December,4,12,Friday
2,2024-04-25,2024,4,April,2,25,Thursday
3,2025-12-18,2025,12,December,4,18,Thursday
4,2024-05-16,2024,5,May,2,16,Thursday

In [28]:
df_clean['revenue'] = df_clean['final_price']

In [29]:
df_clean[['price', 'discount', 'final_price', 'revenue']].head()

      price  discount  final_price   revenue
0  33090.51     10.46     29629.31  29629.31
1   9368.97      5.32      8870.73   8870.73
2  14756.85     26.00     10919.43  10919.43
3    668.83     24.81       502.91    502.91
4  10881.29     48.63      5589.58   5589.58

In [30]:
df_clean['discount_amount'] = (
    df_clean['price'] - df_clean['final_price']
)

In [31]:
df_clean[
    ['price', 'discount', 'discount_amount', 'final_price']
].head()

      price  discount  discount_amount  final_price
0  33090.51     10.46          3461.20     29629.31
1   9368.97      5.32           498.24      8870.73
2  14756.85     26.00          3837.42     10919.43
3    668.83     24.81           165.92       502.91
4  10881.29     48.63          5291.71      5589.58

In [32]:
def classify_shipping(days):
    if days <= 2:
        return 'Fast'
    elif days <= 4:
        return 'Standard'
    else:
        return 'Slow'

df_clean['shipping_category'] = (
    df_clean['shipping_time_days']
    .apply(classify_shipping)
)

In [33]:
df_clean['shipping_category'].value_counts()

shipping_category
Fast        400316
Standard    333442
Slow        266242
Name: count, dtype: int64

In [34]:
def classify_rating(rating):
    if rating < 3:
        return 'Low'
    elif rating < 4:
        return 'Medium'
    else:
        return 'High'

df_clean['rating_category'] = (
    df_clean['rating']
    .apply(classify_rating)
)

In [35]:
df_clean['rating_category'].value_counts()

rating_category
Medium    488788
High      481087
Low        30125
Name: count, dtype: int64

In [36]:
def classify_seller_rating(rating):
    if rating < 3:
        return 'Low'
    elif rating < 4:
        return 'Medium'
    else:
        return 'High'

df_clean['seller_rating_category'] = (
    df_clean['seller_rating']
    .apply(classify_seller_rating)
)

In [37]:
df_clean['return_flag'] = (
    df_clean['is_returned']
    .astype(int)
)

In [38]:
return_rate = df_clean['return_flag'].mean()

print("Return rate:", return_rate)

Return rate: 0.11599

In [39]:
df_clean['delivered_flag'] = (
    df_clean['delivery_status'] == 'Delivered'
).astype(int)

In [40]:
df_clean['delayed_flag'] = (
    df_clean['delivery_status'] == 'Delayed'
).astype(int)

In [41]:
print("Shape setelah transformation:", df_clean.shape)

Shape setelah transformation: (1000000, 34)

In [42]:
df_clean.head()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,...,purchase_day,purchase_day_name,revenue,discount_amount,shipping_category,rating_category,seller_rating_category,return_flag,delivered_flag,delayed_flag
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43,...,4,Tuesday,29629.31,3461.20,Slow,High,High,1,0,0
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13,...,12,Friday,8870.73,498.24,Fast,Medium,High,1,0,0
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46,...,25,Thursday,10919.43,3837.42,Fast,High,High,1,0,0
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6,...,18,Thursday,502.91,165.92,Fast,Medium,Medium,0,0,0
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48,...,16,Thursday,5589.58,5291.71,Slow,High,Low,0,0,1

In [43]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   user_id                 1000000 non-null  object
 1   product_id              1000000 non-null  object
 2   category                1000000 non-null  object
 3   subcategory             1000000 non-null  object
 4   brand                   1000000 non-null  object
 5   price                   1000000 non-null  float64
 6   discount                1000000 non-null  float64
 7   final_price             1000000 non-null  float64
 8   rating                  1000000 non-null  float64
 9   review_count            1000000 non-null  int64
 10  stock                   1000000 non-null  int64
 11  seller_id               1000000 non-null  object
 12  seller_rating           1000000 non-null  float64
 13  purchase_date           1000000 non-null  datetime64[ns]
 14  shipping_time_days      1000000 non-null  int64
 15  location                1000000 non-null  object
 16  device                  1000000 non-null  object
 17  payment_method          1000000 non-null  object
 18  is_returned             1000000 non-null  bool
 19  delivery_status         1000000 non-null  object
 20  purchase_year           1000000 non-null  int32
 21  purchase_month          1000000 non-null  int32
 22  purchase_month_name     1000000 non-null  object
 23  purchase_quarter        1000000 non-null  int32
 24  purchase_day            1000000 non-null  int32
 25  purchase_day_name       1000000 non-null  object
 26  revenue                 1000000 non-null  float64
 27  discount_amount         1000000 non-null  float64
 28  shipping_category       1000000 non-null  object
 29  rating_category         1000000 non-null  object
 30  seller_rating_category  1000000 non-null  object
 31  return_flag             1000000 non-null  int32
 32  delivered_flag          1000000 non-null  int32
 33  delayed_flag            1000000 non-null  int32
dtypes: bool(1), datetime64[ns](1), float64(7), int32(7), int64(3), object(15)
memory usage: 226.0+ MB

In [44]:
print("Missing values after transformation:")
print(df_clean.isnull().sum())

Missing values after transformation:
user_id                   0
product_id                0
category                  0
subcategory               0
brand                     0
price                     0
discount                  0
final_price               0
rating                    0
review_count              0
stock                     0
seller_id                 0
seller_rating             0
purchase_date             0
shipping_time_days        0
location                  0
device                    0
payment_method            0
is_returned               0
delivery_status           0
purchase_year             0
purchase_month            0
purchase_month_name       0
purchase_quarter          0
purchase_day              0
purchase_day_name         0
revenue                   0
discount_amount           0
shipping_category         0
rating_category           0
seller_rating_category    0
return_flag               0
delivered_flag            0
delayed_flag              0
dtype: int64

In [45]:
print("\nShipping category:")
print(df_clean['shipping_category'].value_counts())

print("\nRating category:")
print(df_clean['rating_category'].value_counts())

print("\nReturn flag:")
print(df_clean['return_flag'].value_counts())

print("\nDelivery status:")
print(df_clean['delivery_status'].value_counts())

Shipping category:
shipping_category
Fast        400316
Standard    333442
Slow        266242
Name: count, dtype: int64

Rating category:
rating_category
Medium    488788
High      481087
Low        30125
Name: count, dtype: int64

Return flag:
return_flag
0    884010
1    115990
Name: count, dtype: int64

Delivery status:
delivery_status
Delivered     295234
Delayed       294983
In Transit    293793
Returned      115990
Name: count, dtype: int64

## 6. Data Modeling

In [46]:
# ==========================================
# DIM USER
# ==========================================

dim_user = (
    df_clean[
        [
            'user_id',
            'location',
            'device'
        ]
    ]
    .drop_duplicates('user_id')
    .reset_index(drop=True)
)

# Surrogate key
dim_user.insert(0, 'user_key', range(1, len(dim_user) + 1))

print(dim_user.shape)
dim_user.head()

(603815, 4)

   user_key  user_id   location      device
0         1  U356787  Bangalore      Tablet
1         2  U198246      Delhi      Tablet
2         3  U539898    Chennai  Mobile App
3         4  U325772     Mumbai         Web
4         5  U865179      Delhi         Web

In [47]:
# ==========================================
# DIM PRODUCT
# ==========================================

dim_product = (
    df[
        [
            'product_id',
            'category',
            'subcategory',
            'brand'
        ]
    ]
    .drop_duplicates('product_id')
    .reset_index(drop=True)
)

dim_product.insert(
    0,
    'product_key',
    range(1, len(dim_product) + 1)
)

print(dim_product.shape)
dim_product.head()

(89999, 5)

   product_key product_id     category subcategory    brand
0            1     P39256  Electronics      Mobile      H&M
1            2     P38657       Sports     Outdoor  Samsung
2            3     P38893       Sports     Fitness      H&M
3            4     P54118       Beauty      Makeup     Sony
4            5     P70217         Home       Decor     Sony

In [48]:
# ==========================================
# DIM SELLER
# ==========================================

dim_seller = (
    df_clean[
        [
            'seller_id',
            'seller_rating',
            'seller_rating_category'
        ]
    ]
    .drop_duplicates('seller_id')
    .reset_index(drop=True)
)

dim_seller.insert(
    0,
    'seller_key',
    range(1, len(dim_seller) + 1)
)

print(dim_seller.shape)
dim_seller.head()

(9000, 4)

   seller_key seller_id  seller_rating seller_rating_category
0           1     S2679            4.3                   High
1           2     S9279            4.9                   High
2           3     S5557            4.9                   High
3           4     S2519            3.1                 Medium
4           5     S3045            2.6                    Low

In [49]:
# ==========================================
# DIM DATE
# ==========================================

dim_date = (
    df_clean[
        [
            'purchase_date',
            'purchase_year',
            'purchase_month',
            'purchase_month_name',
            'purchase_quarter',
            'purchase_day',
            'purchase_day_name'
        ]
    ]
    .drop_duplicates('purchase_date')
    .sort_values('purchase_date')
    .reset_index(drop=True)
)

dim_date.insert(
    0,
    'date_key',
    range(1, len(dim_date) + 1)
)

print(dim_date.shape)
dim_date.head()

(731, 8)

,date_key,purchase_date,purchase_year,purchase_month,purchase_month_name,purchase_quarter,purchase_day,purchase_day_name
0,1,2024-03-31,2024,3,March,1,31,Sunday
1,2,2024-04-01,2024,4,April,2,1,Monday
2,3,2024-04-02,2024,4,April,2,2,Tuesday
3,4,2024-04-03,2024,4,April,2,3,Wednesday
4,5,2024-04-04,2024,4,April,2,4,Thursday

In [50]:
fact_sales = df_clean[
    [
        'user_id',
        'product_id',
        'seller_id',
        'purchase_date',
        'price',
        'discount',
        'discount_amount',
        'final_price',
        'revenue',
        'rating',
        'review_count',
        'stock',
        'shipping_time_days',
        'shipping_category',
        'payment_method',
        'device',
        'delivery_status',
        'is_returned',
        'return_flag',
        'delivered_flag',
        'delayed_flag'
    ]
].copy()

In [51]:
#Ganti ID dengan Surrogate Key

#User
fact_sales = fact_sales.merge(
    dim_user[['user_key', 'user_id']],
    on='user_id',
    how='left'
)

#Product
fact_sales = fact_sales.merge(
    dim_product[['product_key', 'product_id']],
    on='product_id',
    how='left'
)

#Seller
fact_sales = fact_sales.merge(
    dim_seller[['seller_key', 'seller_id']],
    on='seller_id',
    how='left'
)

#Date
fact_sales = fact_sales.merge(
    dim_date[['date_key', 'purchase_date']],
    on='purchase_date',
    how='left'
)

In [52]:
fact_sales = fact_sales[
    [
        'user_key',
        'product_key',
        'seller_key',
        'date_key',
        'price',
        'discount',
        'discount_amount',
        'final_price',
        'revenue',
        'rating',
        'review_count',
        'stock',
        'shipping_time_days',
        'shipping_category',
        'payment_method',
        'device',
        'delivery_status',
        'is_returned',
        'return_flag',
        'delivered_flag',
        'delayed_flag'
    ]
]

In [53]:
fact_sales.insert(
    0,
    'sales_key',
    range(1, len(fact_sales) + 1)
)

In [54]:
print("dim_user:", dim_user.shape)
print("dim_product:", dim_product.shape)
print("dim_seller:", dim_seller.shape)
print("dim_date:", dim_date.shape)
print("fact_sales:", fact_sales.shape)

dim_user: (603815, 4)
dim_product: (89999, 5)
dim_seller: (9000, 4)
dim_date: (731, 8)
fact_sales: (1000000, 22)

In [55]:
fact_sales.head()

,sales_key,user_key,product_key,seller_key,date_key,price,discount,discount_amount,final_price,revenue,...,stock,shipping_time_days,shipping_category,payment_method,device,delivery_status,is_returned,return_flag,delivered_flag,delayed_flag
0,1,1,1,1,339,33090.51,10.46,3461.20,29629.31,29629.31,...,71,6,Slow,UPI,Tablet,Returned,True,1,0,0
1,2,2,2,2,622,9368.97,5.32,498.24,8870.73,8870.73,...,119,1,Fast,UPI,Tablet,Returned,True,1,0,0
2,3,3,3,3,26,14756.85,26.00,3837.42,10919.43,10919.43,...,229,1,Fast,Credit Card,Mobile App,Returned,True,1,0,0
3,4,4,4,4,628,668.83,24.81,165.92,502.91,502.91,...,52,2,Fast,UPI,Web,In Transit,False,0,0,0
4,5,5,5,5,47,10881.29,48.63,5291.71,5589.58,5589.58,...,274,5,Slow,UPI,Web,Delayed,False,0,0,1

## 7. Save Data

In [56]:
print("\n" + "=" * 60)
print("7. SAVE DATA TO CSV")
print("=" * 60)

# Create directories
os.makedirs('../data/staging', exist_ok=True)
os.makedirs('../data/warehouse', exist_ok=True)

# 7.1 Save staging data (cleaned & transformed data)
staging_path = '../data/staging/ecommerce_staging.csv'
df_clean.to_csv(staging_path, index=False)
print(f"✓ Staging data saved to: {staging_path}")
print(f"  Shape: {df_clean.shape}")

# 7.2 Save dimension tables
dim_tables = {
    'dim_user': dim_user,
    'dim_product': dim_product,
    'dim_seller': dim_seller,
    'dim_date': dim_date
}

for name, table in dim_tables.items():
    filepath = f'../data/warehouse/{name}.csv'
    table.to_csv(filepath, index=False)
    print(f"✓ {name} saved to: {filepath}")
    print(f"  Shape: {table.shape}")

# 7.3 Save fact table
fact_path = '../data/warehouse/fact_sales.csv'
fact_sales.to_csv(fact_path, index=False)
print(f"✓ fact_sales saved to: {fact_path}")
print(f"  Shape: {fact_sales.shape}")

============================================================
7. SAVE DATA TO CSV
============================================================
✓ Staging data saved to: ../data/staging/ecommerce_staging.csv
  Shape: (1000000, 34)
✓ dim_user saved to: ../data/warehouse/dim_user.csv
  Shape: (603815, 4)
✓ dim_product saved to: ../data/warehouse/dim_product.csv
  Shape: (89999, 5)
✓ dim_seller saved to: ../data/warehouse/dim_seller.csv
  Shape: (9000, 4)
✓ dim_date saved to: ../data/warehouse/dim_date.csv
  Shape: (731, 8)
✓ fact_sales saved to: ../data/warehouse/fact_sales.csv
  Shape: (1000000, 22)